#pragma once

#include <set>
#include <map>
#include <span>
#include <tuple>
#include <print>
#include <cmath>
#include <array>
#include <vector>
#include <chrono>
#include <thread>
#include <cctype>
#include <string>
#include <cstdint>
#include <cstddef>
#include <cstring>
#include <cassert>
#include <fstream>
#include <optional>
#include <algorithm>
#include <string_view>